//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefPropWindowsForms.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefPropWindowsForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cascade_Cycle_Small {
            get {
                object obj = ResourceManager.GetObject("Cascade Cycle Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Collector_Details_LF {
            get {
                object obj = ResourceManager.GetObject("Collector Details LF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Collector_Details_PTC {
            get {
                object obj = ResourceManager.GetObject("Collector Details PTC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Collector_Details_PTC1 {
            get {
                object obj = ResourceManager.GetObject("Collector Details PTC1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Compressor_Results_Summary {
            get {
                object obj = ResourceManager.GetObject("Compressor Results Summary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Config52_Ref_L_Veseley_SimpleBrayton {
            get {
                object obj = ResourceManager.GetObject("Config52_Ref_L_Veseley_SimpleBrayton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Config53_Ref_L_Veseley_Brayton {
            get {
                object obj = ResourceManager.GetObject("Config53_Ref_L_Veseley_Brayton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ED_Main_Inputs_LF {
            get {
                object obj = ResourceManager.GetObject("ED Main Inputs LF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ED_Main_Inputs_PTC {
            get {
                object obj = ResourceManager.GetObject("ED Main Inputs PTC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Figure_2_RC_Brayton {
            get {
                object obj = ResourceManager.GetObject("Figure 2.RC Brayton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flow_Path_Hardware {
            get {
                object obj = ResourceManager.GetObject("Flow_Path_Hardware", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Forristal_receiver_model {
            get {
                object obj = ResourceManager.GetObject("Forristal_receiver_model", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Generator {
            get {
                object obj = ResourceManager.GetObject("Generator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Generator_RPM {
            get {
                object obj = ResourceManager.GetObject("Generator RPM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HX_Results_Summary {
            get {
                object obj = ResourceManager.GetObject("HX Results Summary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kimzey_Cycle_Small {
            get {
                object obj = ResourceManager.GetObject("Kimzey Cycle Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LF_Collector_Details_Tab {
            get {
                object obj = ResourceManager.GetObject("LF_Collector_Details_Tab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LF_Flowpaht_Hardware_Design {
            get {
                object obj = ResourceManager.GetObject("LF_Flowpaht_Hardware_Design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LF_Irradiance_Tab {
            get {
                object obj = ResourceManager.GetObject("LF_Irradiance_Tab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Linear_Fresnel_Solar_Field {
            get {
                object obj = ResourceManager.GetObject("Linear_Fresnel_Solar_Field", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_UPM_Small {
            get {
                object obj = ResourceManager.GetObject("Logo UPM Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_ReHeating {
            get {
                object obj = ResourceManager.GetObject("PCRC with ReHeating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_ReHeating_ICAI_proposed_configuration {
            get {
                object obj = ResourceManager.GetObject("PCRC with ReHeating ICAI proposed configuration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_ReHeating_ICAI_proposed_configuration_Small {
            get {
                object obj = ResourceManager.GetObject("PCRC with ReHeating ICAI proposed configuration Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRC with ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_ReHeating_Small1 {
            get {
                object obj = ResourceManager.GetObject("PCRC with ReHeating Small1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_ReHeating_with_Three_Reheating_Stages {
            get {
                object obj = ResourceManager.GetObject("PCRC with ReHeating with Three Reheating Stages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_ReHeating_with_Three_Reheating_Stages_Small {
            get {
                object obj = ResourceManager.GetObject("PCRC with ReHeating with Three Reheating Stages Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_ReHeating_with_Two_Reheating_Stages {
            get {
                object obj = ResourceManager.GetObject("PCRC with ReHeating with Two Reheating Stages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_ReHeating_with_Two_Reheating_Stages_Small {
            get {
                object obj = ResourceManager.GetObject("PCRC with ReHeating with Two Reheating Stages Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_RH_Small {
            get {
                object obj = ResourceManager.GetObject("PCRC with RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_Three_RH {
            get {
                object obj = ResourceManager.GetObject("PCRC with Three RH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_Two_Intercooling_and_Reheating_Stages {
            get {
                object obj = ResourceManager.GetObject("PCRC with Two Intercooling and Reheating Stages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_Two_Intercooling_and_Reheating_Stages_Small {
            get {
                object obj = ResourceManager.GetObject("PCRC with Two Intercooling and Reheating Stages Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_Two_Intercooling_and_RH_Small {
            get {
                object obj = ResourceManager.GetObject("PCRC with Two Intercooling and RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_Two_Intercooling_and_Two_Reheating {
            get {
                object obj = ResourceManager.GetObject("PCRC with Two Intercooling and Two Reheating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_Two_Intercooling_and_Two_Reheating_Stages {
            get {
                object obj = ResourceManager.GetObject("PCRC with Two Intercooling and Two Reheating Stages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_Two_Intercooling_and_Two_Reheating_Stages_Small {
            get {
                object obj = ResourceManager.GetObject("PCRC with Two Intercooling and Two Reheating Stages Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_Two_Intercooling_and_without_RH_Small {
            get {
                object obj = ResourceManager.GetObject("PCRC with Two Intercooling and without RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_Two_Intercooling_Without_Reheating {
            get {
                object obj = ResourceManager.GetObject("PCRC with Two Intercooling Without Reheating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_Two_Intercooling_Without_Reheating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRC with Two Intercooling Without Reheating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_with_Two_RH {
            get {
                object obj = ResourceManager.GetObject("PCRC with Two RH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_without_ReHeating {
            get {
                object obj = ResourceManager.GetObject("PCRC without ReHeating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_without_ReHeating_ICAI_proposed_configuration {
            get {
                object obj = ResourceManager.GetObject("PCRC without ReHeating ICAI proposed configuration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_without_ReHeating_ICAI_proposed_configuration_Small {
            get {
                object obj = ResourceManager.GetObject("PCRC without ReHeating ICAI proposed configuration Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_without_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRC without ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRC_without_RH_Small {
            get {
                object obj = ResourceManager.GetObject("PCRC without RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_Two_Intercooling_without_RH_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI Two Intercooling without RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_ReHeating {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with ReHeating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_ReHeating_Icon {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with ReHeating_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_ReHeating_Small1 {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with ReHeating Small1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_RH_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Three_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Three ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Three_RH_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Three RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Intercooling_with_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Intercooling with ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Intercooling_with_Three_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Intercooling with Three ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Intercooling_with_Two_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Intercooling with Two ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Intercooling_without_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Intercooling without ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Partial_Cooling_with_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Partial Cooling with ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Partial_Cooling_with_Three_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Partial Cooling with Three ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Partial_Cooling_with_Two_Intercooling_with_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Partial Cooling with Two Intercooling with ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Partial_Cooling_with_Two_Intercooling_with_ReHeating_Small1 {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Partial Cooling with Two Intercooling with ReHeating Small1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Partial_Cooling_with_Two_Intercooling_with_Three_ReHeating_Icon {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Partial Cooling with Two Intercooling with Three ReHeating_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Partial_Cooling_with_Two_Intercooling_with_Three_ReHeating_Icon1 {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Partial Cooling with Two Intercooling with Three ReHeating_Icon1" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Partial_Cooling_with_Two_Intercooling_with_Three_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Partial Cooling with Two Intercooling with Three ReHeating Small" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Partial_Cooling_with_Two_Intercooling_with_Two_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Partial Cooling with Two Intercooling with Two ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Partial_Cooling_with_Two_Intercooling_without_ReHeating_Icon {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Partial Cooling with Two Intercooling without ReHeating_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Partial_Cooling_with_Two_Intercooling_without_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Partial Cooling with Two Intercooling without ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Partial_Cooling_with_Two_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Partial Cooling with Two ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Partial_Cooling_without_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Partial Cooling without ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_Partial_Cooling_without_ReHeating_Small1 {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two Partial Cooling without ReHeating Small1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_ReHeating__Stages {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two ReHeating  Stages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_with_Two_RH_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI with Two RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_without_ReHeating {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI without ReHeating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_without_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI without ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_without_ReHeating_Small1 {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI without ReHeating Small1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_without_ReHeating_Small2 {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI without ReHeating Small2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCRCMCI_without_RH_Small {
            get {
                object obj = ResourceManager.GetObject("PCRCMCI without RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PHX_interface_with_BOP {
            get {
                object obj = ResourceManager.GetObject("PHX_interface_with_BOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PHX_interface_with_BOP1 {
            get {
                object obj = ResourceManager.GetObject("PHX_interface_with_BOP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PHX_interface_with_BOP2 {
            get {
                object obj = ResourceManager.GetObject("PHX_interface_with_BOP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PHX_interface_with_BOP3 {
            get {
                object obj = ResourceManager.GetObject("PHX_interface_with_BOP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Prueba {
            get {
                object obj = ResourceManager.GetObject("Prueba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PTC_SF_Results_Summary {
            get {
                object obj = ResourceManager.GetObject("PTC SF Results Summary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PTC_SF_Results_Summary1 {
            get {
                object obj = ResourceManager.GetObject("PTC SF Results Summary1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_final {
            get {
                object obj = ResourceManager.GetObject("RC final", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_final1 {
            get {
                object obj = ResourceManager.GetObject("RC final1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_PreHeating_in_parallel_with_HTR_without_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("RC with PreHeating in parallel with HTR without ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_PreHeating_in_parallel_with_LTR_and_HTR_without_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("RC with PreHeating in parallel with LTR and HTR without ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_PreHeating_in_parallel_with_LTR_and_Three_Recuperators_Small {
            get {
                object obj = ResourceManager.GetObject("RC with PreHeating in parallel with LTR and Three Recuperators Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_PreHeating_in_parallel_with_LTR_with_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("RC with PreHeating in parallel with LTR with ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_PreHeating_in_parallel_with_LTR_without_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("RC with PreHeating in parallel with LTR without ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_ReHeating {
            get {
                object obj = ResourceManager.GetObject("RC with ReHeating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_ReHeating_ICAI_proposed_configuration {
            get {
                object obj = ResourceManager.GetObject("RC with ReHeating ICAI proposed configuration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_ReHeating_ICAI_proposed_configuration_Small {
            get {
                object obj = ResourceManager.GetObject("RC with ReHeating ICAI proposed configuration Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_ReHeating_ICAI_proposed_configuration1 {
            get {
                object obj = ResourceManager.GetObject("RC with ReHeating ICAI proposed configuration1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_ReHeating_ICAI_proposed_configuration2 {
            get {
                object obj = ResourceManager.GetObject("RC with ReHeating ICAI proposed configuration2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_ReHeating1 {
            get {
                object obj = ResourceManager.GetObject("RC with ReHeating1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_ReHeating1_Small {
            get {
                object obj = ResourceManager.GetObject("RC with ReHeating1 Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_ReHeating2 {
            get {
                object obj = ResourceManager.GetObject("RC with ReHeating2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_ReHeating3 {
            get {
                object obj = ResourceManager.GetObject("RC with ReHeating3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_RH_Small {
            get {
                object obj = ResourceManager.GetObject("RC with RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_Three_ReHeating_Stages {
            get {
                object obj = ResourceManager.GetObject("RC with Three ReHeating Stages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_Three_ReHeating_Stages_Small {
            get {
                object obj = ResourceManager.GetObject("RC with Three ReHeating Stages Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_Three_RH_Small {
            get {
                object obj = ResourceManager.GetObject("RC with Three RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_Two_ReHeating_Stages {
            get {
                object obj = ResourceManager.GetObject("RC with Two ReHeating Stages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_Two_ReHeating_Stages_Icon {
            get {
                object obj = ResourceManager.GetObject("RC with Two ReHeating Stages_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_Two_ReHeating_Stages_Small {
            get {
                object obj = ResourceManager.GetObject("RC with Two ReHeating Stages Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_with_Two_RH_Small {
            get {
                object obj = ResourceManager.GetObject("RC with Two RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_without_ReHeating {
            get {
                object obj = ResourceManager.GetObject("RC without ReHeating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_without_ReHeating_Case_4_Mecheri_Small {
            get {
                object obj = ResourceManager.GetObject("RC without ReHeating-Case 4-Mecheri Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_without_ReHeating_ICAI_proposed_configuration {
            get {
                object obj = ResourceManager.GetObject("RC without ReHeating ICAI proposed configuration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_without_ReHeating_ICAI_proposed_configuration_Small {
            get {
                object obj = ResourceManager.GetObject("RC without ReHeating ICAI proposed configuration Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_without_ReHeating_ICAI_proposed_configuration1 {
            get {
                object obj = ResourceManager.GetObject("RC without ReHeating ICAI proposed configuration1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_without_ReHeating_ICAI_proposed_configuration2 {
            get {
                object obj = ResourceManager.GetObject("RC without ReHeating ICAI proposed configuration2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_without_ReHeating_Icon {
            get {
                object obj = ResourceManager.GetObject("RC without ReHeating_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_without_ReHeating_Icon1 {
            get {
                object obj = ResourceManager.GetObject("RC without ReHeating_Icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_without_ReHeating_Icon2 {
            get {
                object obj = ResourceManager.GetObject("RC without ReHeating_Icon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_without_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("RC without ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RC_without_RH_Small {
            get {
                object obj = ResourceManager.GetObject("RC without RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_ReHeating {
            get {
                object obj = ResourceManager.GetObject("RCMCI with ReHeating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_ReHeating_ICAI_proposed_configuration {
            get {
                object obj = ResourceManager.GetObject("RCMCI with ReHeating ICAI proposed configuration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_ReHeating_ICAI_proposed_configuration_Small {
            get {
                object obj = ResourceManager.GetObject("RCMCI with ReHeating ICAI proposed configuration Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_ReHeating_ICAI_proposed_configuration_Small_luis {
            get {
                object obj = ResourceManager.GetObject("RCMCI with ReHeating ICAI proposed configuration Small luis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_ReHeating_ICAI_proposed_configuration_Small1 {
            get {
                object obj = ResourceManager.GetObject("RCMCI with ReHeating ICAI proposed configuration Small1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("RCMCI with ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_ReHeating_Small1 {
            get {
                object obj = ResourceManager.GetObject("RCMCI with ReHeating Small1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_ReHeating_Small11 {
            get {
                object obj = ResourceManager.GetObject("RCMCI with ReHeating Small11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_ReHeating_Small2 {
            get {
                object obj = ResourceManager.GetObject("RCMCI with ReHeating Small2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_ReHeating_with_Three_Reheating_Stages {
            get {
                object obj = ResourceManager.GetObject("RCMCI with ReHeating with Three Reheating Stages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_ReHeating_with_Three_Reheating_Stages_Small {
            get {
                object obj = ResourceManager.GetObject("RCMCI with ReHeating with Three Reheating Stages Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_ReHeating_with_Two_Reheating_Stages {
            get {
                object obj = ResourceManager.GetObject("RCMCI with ReHeating with Two Reheating Stages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_ReHeating_with_Two_Reheating_Stages_Small {
            get {
                object obj = ResourceManager.GetObject("RCMCI with ReHeating with Two Reheating Stages Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_Three_ReHeating_Small2 {
            get {
                object obj = ResourceManager.GetObject("RCMCI with Three ReHeating Small2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_Two_Intercooling_and_ReHeating {
            get {
                object obj = ResourceManager.GetObject("RCMCI with Two Intercooling and ReHeating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_Two_Intercooling_and_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("RCMCI with Two Intercooling and ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_Two_Intercooling_and_ReHeating_Small2 {
            get {
                object obj = ResourceManager.GetObject("RCMCI with Two Intercooling and ReHeating Small2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_Two_Intercooling_and_Two_ReHeating_Small2 {
            get {
                object obj = ResourceManager.GetObject("RCMCI with Two Intercooling and Two ReHeating Small2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_Two_Intercooling_and_Two_Reheating_Stages {
            get {
                object obj = ResourceManager.GetObject("RCMCI with Two Intercooling and Two Reheating Stages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_Two_Intercooling_and_Two_Reheating_Stages_Small {
            get {
                object obj = ResourceManager.GetObject("RCMCI with Two Intercooling and Two Reheating Stages Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_Two_Intercooling_and_without_ReHeating {
            get {
                object obj = ResourceManager.GetObject("RCMCI with Two Intercooling and without ReHeating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_Two_Intercooling_without_ReHeating {
            get {
                object obj = ResourceManager.GetObject("RCMCI with Two Intercooling without ReHeating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_Two_Intercooling_without_ReHeating_Icon {
            get {
                object obj = ResourceManager.GetObject("RCMCI with Two Intercooling without ReHeating_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_with_Two_Intercooling_without_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("RCMCI with Two Intercooling without ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_without_ReHeating {
            get {
                object obj = ResourceManager.GetObject("RCMCI without ReHeating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_without_ReHeating_ICAI_proposed_configuration {
            get {
                object obj = ResourceManager.GetObject("RCMCI without ReHeating ICAI proposed configuration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_without_ReHeating_ICAI_proposed_configuration_Small {
            get {
                object obj = ResourceManager.GetObject("RCMCI without ReHeating ICAI proposed configuration Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RCMCI_without_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("RCMCI without ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SB_with_PreHeating_in_parallel_with_LTR_and_HTR_without_ReHeating {
            get {
                object obj = ResourceManager.GetObject("SB with PreHeating in parallel with LTR and HTR without ReHeating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SB_with_PreHeating_in_parallel_with_LTR_and_HTR_without_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("SB with PreHeating in parallel with LTR and HTR without ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SB_with_PreHeating_in_parallel_with_LTR_without_ReHeating {
            get {
                object obj = ResourceManager.GetObject("SB with PreHeating in parallel with LTR without ReHeating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SB_with_PreHeating_in_parallel_with_LTR_without_ReHeating_Small {
            get {
                object obj = ResourceManager.GetObject("SB with PreHeating in parallel with LTR without ReHeating Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SNL_compressor_Performance_Map {
            get {
                object obj = ResourceManager.GetObject("SNL compressor Performance Map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Titulo_Turbina {
            get {
                object obj = ResourceManager.GetObject("Titulo_Turbina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Turbine_Map {
            get {
                object obj = ResourceManager.GetObject("Turbine_Map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Turbine_Map1 {
            get {
                object obj = ResourceManager.GetObject("Turbine_Map1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Turbine_Results_Summary {
            get {
                object obj = ResourceManager.GetObject("Turbine Results Summary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Turbine_Results_Summary1 {
            get {
                object obj = ResourceManager.GetObject("Turbine Results Summary1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Two_Intercooling_PCRCMCI_with_Two_Intercooling_without_RH_Small {
            get {
                object obj = ResourceManager.GetObject("Two Intercooling PCRCMCI with Two Intercooling without RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Two_Intercooling_PCRCMCI_without_RH_Small {
            get {
                object obj = ResourceManager.GetObject("Two Intercooling PCRCMCI without RH Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TwoDimensionHeatEquation {
            get {
                object obj = ResourceManager.GetObject("TwoDimensionHeatEquation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TwoDimensionHeatModel {
            get {
                object obj = ResourceManager.GetObject("TwoDimensionHeatModel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TwoDimensionHeatModel1 {
            get {
                object obj = ResourceManager.GetObject("TwoDimensionHeatModel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
